# =============================================================================
# ANA AYARLAR DOSYASI
# TR: Sitenizin tüm kişisel bilgilerini bu tek dosyadan yönetebilirsiniz.
# EN: You can manage all your site's personal information from this single file.
# =============================================================================

# -----------------------------------------------------------------------------
# Profil Bilgileri
# TR: Sitenin sahibi hakkında genel bilgiler. Avatar, isim, e-posta vb.
# EN: General information about the site owner. Avatar, name, email, etc.
# -----------------------------------------------------------------------------
profile:
  name: "Muhammet Abdullah Şahin"
  short_name: "M.A. Şahin"
  email: "m.sahinabdullah@gmail.com"
  phone: # "+90 999 999 9999" # İsteğe bağlı
  avatar: "/assets/images/profile.png"

# -----------------------------------------------------------------------------
# Sosyal Medya Linkleri
# TR: Sitenizde görünecek sosyal medya ikonları ve linkleri.
# EN: Social media icons and links to be displayed on your site.
# -----------------------------------------------------------------------------
social_links:
  - name: "GitHub"
    url: "https://github.com/SahinMuhammetAbdullah"
    bg_color: "ctp-blue"
    hover_bg_color: "ctp-sapphire"
    icon_class: "fab fa-github"
  - name: "LinkedIn"
    url: "https://linkedin.com/in/muhammet-abdullah-sahin"
    bg_color: "ctp-mauve"
    hover_bg_color: "ctp-pink"
    icon_class: "fab fa-linkedin"
  - name: "Resume"
    url: "https://cv.masahin.dev"
    bg_color: "ctp-green"
    hover_bg_color: "ctp-teal"
    icon_class: "fas fa-file-lines"
  - name: "Blog"
    url: "https://blog.masahin.dev"
    bg_color: "ctp-red"
    hover_bg_color: "ctp-maroon"
    icon_class: "fas fa-blog"
  # - name: "Website"
  #   url: "https://sahinmuhammetabdullah.github.io/"
  #   icon_class: "fas fa-globe"

# -----------------------------------------------------------------------------
# Çok Dilli İçerikler
# TR: Bu bölüm, farklı dillerde gösterilecek metinleri içerir.
# EN: This section contains texts to be displayed in different languages.
# -----------------------------------------------------------------------------
multilingual_content:
  tr:
    profile:
      greeting_intro: "Merhaba, ben"
      tagline: "Full Stack Geliştirici & Yapay Zeka Araştırmacısı"
      about_title: "Ben Kimim?"
      about_bio_1: "Yapay zeka, siber güvenlik ve web teknolojilerini birleştirerek yenilikçi çözümler üreten bir geliştiriciyim. Sistemlerin sadece çalışmasını değil, aynı zamanda verimli, güvenli ve sürdürülebilir olmasını hedeflerim."
      about_bio_2: "SOC analizlerinden URL malware tespit sistemlerine, davranış analitiğinden ERP yazılımlarına kadar birçok alanda üretken projeler geliştirdim. Kod kalitesi, açık kaynak felsefesi ve sürekli öğrenme benim için vazgeçilmezdir."
      skills:
        frontend:
          title: "Ön Yüz (Frontend)"
          items: "HTML5, CSS3, JavaScript (ES6+), React, Next.js, Tailwind CSS, Jekyll, Liquid"
        backend:
          title: "Arka Yüz (Backend)"
          items: "Node.js, Python, Go, Java, Rust, Ruby"
        database:
          title: "Veritabanı & Araçlar"
          items: "MySQL, PostgreSQL, MsSQL, Docker, Git, Linux, Wireshark, Figma"
      contact_intro: "Projeler, açık kaynak geliştirme, yapay zeka ya da güvenlik konularında sohbet etmek istersen bana her zaman ulaşabilirsin. Bilgiyi paylaşmak ve üretmek, gelişimin en güçlü adımıdır."
      footer_tagline: "Full Stack Geliştirici & Yapay Zeka Araştırmacısı"
      footer_copyright: "© {{ current_year }} Muhammet Abdullah Şahin. Tüm hakları saklıdır."
    navigation_links:
      - title: "Hakkımda"
        url: "#about"
      - title: "Projeler"
        url: "#projects"
      - title: "İletişim"
        url: "#contact"

  en:
    profile:
      greeting_intro: "Hi, I'm"
      tagline: "Full Stack Developer & AI Researcher"
      about_title: "Who Am I?"
      about_bio_1: "I’m a developer who combines artificial intelligence, cybersecurity, and modern web technologies to build intelligent and secure systems. My focus is on creating efficient, scalable, and sustainable solutions."
      about_bio_2: "I have developed diverse projects ranging from SOC analysis and malicious URL detection systems to behavioral analytics and ERP platforms. I value clean code, open-source collaboration, and continuous learning."
      skills:
        frontend:
          title: "Frontend"
          items: "HTML5, CSS3, JavaScript (ES6+), React, Next.js, Tailwind CSS, Jekyll, Liquid"
        backend:
          title: "Backend"
          items: "Node.js, Python, Go, Java, Rust, Ruby"
        database:
          title: "Database & Tools"
          items: "MySQL, PostgreSQL, MsSQL, Docker, Git, Linux, Wireshark, Figma"
      contact_intro: "Feel free to reach out if you’d like to discuss projects, open-source development, AI research, or cybersecurity. Sharing and creating knowledge is the foundation of growth."
      footer_tagline: "Full Stack Developer & AI Researcher"
      footer_copyright: "© {{ current_year }} Muhammet Abdullah Şahin. All rights reserved."
    navigation_links:
      - title: "About"
        url: "#about"
      - title: "Projects"
        url: "#projects"
      - title: "Contact"
        url: "#contact"

